project-name: Portfolio
base-path: /
context:
  static:
    author: Dennoh Peter
    website: https://www.dennohpeter.com
    mail: mail@dennohpeter.com
    github: https://github.com/dennohpeter
    gitlab: https://gitlab.com/dennohpeter
    twitter: https://twitter.com/dennohpeter
    devpost: https://devpost.com/dennohpeter
    linkedIn: https://www.linkedin.com/in/dennohpeter
